CONTRIBUTING.md, README.md, package-lock.json, package.json
commitizen + cz-lerna-changelog
ISSUES CLOSED: #19
-----
Use `npx git-cz` instead of `git commit` to create a conventional commit.
Will automatically detect what packages has been changed. Changed packages can also be adjusted manually.
Bumping version / generating changelog can be tested with `lerna version --conventional-commits --no-push --no-git-tag-version`.
=> chore: setup conventional commits tooling

packages/cuba-react/src/ui/table/DataTableCustomFilter.tsx
applying custom filter in a DataTable placed inside a form
was causing the form to submit
ISSUES CLOSED: #32
=> fix: prevent submitting the form when applying table filter

README.md
the props itself has been previously removed
this commit fixes the documentation
ISSUES CLOSED: #34
=> docs: remove references to DataTable's defaultSort prop from README

packages/cuba-react/src/ui/table/DataTableListEditor.tsx
=> fix(DataTable): not possible to enter 0 in the custom filter list editor on number field

packages/front-generator/src/generators/react-typescript/app/template/package-lock.json
Locks @formatjs/intl-utils at ^1.6.0. To be reverted once the issue is fixed.
=> chore(React): work around formatjs/react-intl#1548

packages/cuba-react/src/ui/EntityProperty.tsx
do not show entity property if metadata or other required data are not ready in main store
ISSUES CLOSED: #54
=> Hide property if metadata not loaded (quickfix)

packages/cuba-react/src/app/Security.ts
role permission checks will not be applied untill effective permissions implementation in next
version
=> [Master] fix(React): reverted role permission checks

.travis.yml, README.md, package.json, packages/cuba-rest-js/package.json, packages/front-generator/package.json
affects: @cuba-platform/rest, @cuba-platform/front-generator
relates: #3
BREAKING CHANGE:
required nodejs version 12+
=> Use node js 12+

packages/front-generator/src/generators/react-typescript/app/template/package.json
=> fix TypeError [ERR_INVALID_ARG_TYPE] on app startup

packages/cuba-react-core/src/data/Collection.tsx, packages/cuba-react-ui/src/ui/table/DataTable.tsx, packages/front-generator/src/generators/react-typescript/app/template/src/i18n/en.json, packages/front-generator/src/generators/react-typescript/app/template/src/i18n/ru.json, packages/front-generator/src/generators/react-typescript/entity-management/template/Cards.tsx.ejs, packages/front-generator/src/generators/react-typescript/entity-management/template/List.tsx.ejs
affects: @cuba-platform/react-core, @cuba-platform/react-ui, @cuba-platform/front-generator
=> fix: no error message when request failed in entity browser

docs-src/antora-playbook.yml, docs-src/supplemental-ui/partials/footer-scripts.hbs, docs-src/supplemental-ui/partials/head-styles.hbs, docs-src/supplemental-ui/partials/header-content.hbs
related to #173
You can build the site locally (`npm run doc:site`) and play with the search (it will use the index of and will redirect to the deployed docs site).
=> docs: add search

packages/cuba-rest-js/dist-browser/cuba.js, packages/cuba-rest-js/dist-node/cuba.js, packages/cuba-rest-js/src/cuba.ts
affects: @cuba-platform/react, @cuba-platform/rest
getRoles and getPermissions methods is noop in case of new CUBA REST permission model
=> fix(React): backward compatibility for CUBA REST 7.2 permission model

commitlint.config.js, docs-src/doc-component-repo/modules/generator/pages/commands-reference.adoc, packages/front-generator/src/common/cli-options.ts
yeoman doesn't support two-letter shortcuts, started from the same letter, all shortcuts changed to single letter
relates: #175
=> fix(React): two letter options (-vb -ds) not work in generator cli

packages/front-generator/src/generators/react-typescript/blank-component/index.ts, packages/front-generator/src/generators/react-typescript/blank-component/template/Component.tsx, packages/front-generator/src/generators/react-typescript/entity-management/index.ts, packages/front-generator/src/generators/react-typescript/entity-management/template-model.ts, packages/front-generator/src/generators/react-typescript/entity-management/template/Cards.tsx.ejs, packages/front-generator/src/generators/react-typescript/entity-management/template/EntityManagement.tsx.ejs, packages/front-generator/src/generators/react-typescript/entity-management/template/EntityManagementEditor.tsx.ejs, packages/front-generator/src/generators/react-typescript/entity-management/template/List.tsx.ejs, packages/front-generator/src/generators/react-typescript/entity-management/template/Table.tsx.ejs, packages/front-generator/src/test/fixtures/answers.json, packages/front-generator/src/test/fixtures/react-client/src/app/entity-management/CarEditLowCase.tsx, packages/front-generator/src/test/fixtures/react-client/src/app/entity-management/CarManagementLowCase.tsx, packages/front-generator/src/test/fixtures/react-client/src/app/entity-management/CarTableLowCase.tsx, packages/front-generator/src/test/generators/react-typrscript/react-generator-process-templates.test.ts, packages/front-generator/src/test/generators/react-typrscript/react-generator.test.ts
generate editor and list classes and files always from capital letter and in camel case notation
relates: #201
BREAKING CHANGE:
component generation - names of component classes and files will be generated in camel case notation with first capital letter
=> fix(Front Generator): capitalize component class names

packages/cuba-react-ui/src/ui/form/Form.tsx, packages/front-generator/src/generators/react-typescript/entity-management/template/EntityManagementEditor.tsx.ejs
affects: @cuba-platform/react-ui, @cuba-platform/front-generator
ticket #213
=> fix: can't save a new entity with a non-empty O2M Composition field

.snyk-react-client-scr, packages/front-generator/src/generators/react-typescript/entity-management/template/Cards.tsx.ejs, packages/front-generator/src/generators/react-typescript/entity-management/template/List.tsx.ejs, packages/front-generator/src/generators/react-typescript/entity-management/template/Table.tsx.ejs, packages/front-generator/src/test/fixtures/mpg-projectModel.json
entity browsers sort will not applied for non-updatable entities
relates: #120
BREAKING CHANGE:
entity browser sort will not applied for projects generated in Studio before 13 version| studio 12 has an issue with correct defining updatable for entities in project model
=> Default sort fail if entity not implements updatable

packages/front-generator/src/generators/react-native/app/index.ts
=> fix: react-native:app asks to select the project twice

packages/front-generator/src/generators/react-typescript/entity-management/index.ts, packages/front-generator/src/test/generators/react-typrscript/entity-management/index.test.ts
Do not ask for the nested entity view if the Composition attribute
is not present in the selected views.
Related to #212.
=> fix: unnecessary question during the entity-management generation

packages/front-generator/src/generators/react-typescript/app/template/src/index.css
=> fix: layout breaks when side menu is bigger than the viewport

packages/front-generator/src/generators/react-typescript/app/template/src/index.css
This reverts commit 9378b9556632df4747f38381b811bfdae54ef5db.
=> Revert "fix: layout breaks when side menu is bigger than the viewport"

docs-src/supplemental-ui/partials/footer-scripts.hbs, docs-src/supplemental-ui/partials/head-scripts.hbs, docs-src/supplemental-ui/partials/head-styles.hbs, docs-src/supplemental-ui/partials/header-content.hbs
use Tag Manager instead of Global Site Tag
ISSUES CLOSED: #263
=> setup analytics on the documentation site

packages/front-generator/src/common/utils.ts, packages/front-generator/src/generators/polymer2/blank-component/index.ts, packages/front-generator/src/generators/polymer2/entity-cards/index.ts, packages/front-generator/src/generators/polymer2/entity-edit/index.ts, packages/front-generator/src/generators/polymer2/entity-list/index.ts, packages/front-generator/src/generators/polymer2/entity-management/index.ts, packages/front-generator/src/generators/polymer2/query-results/index.ts, packages/front-generator/src/generators/polymer2/service-data/index.ts, packages/front-generator/src/generators/polymer2/service-form/index.ts, packages/front-generator/src/generators/react-typescript/blank-component/index.ts, packages/front-generator/src/generators/react-typescript/entity-cards/index.ts, packages/front-generator/src/generators/react-typescript/entity-management/index.ts, packages/front-generator/src/test/utils.test.ts
model relative path, used for import generation in ejs templates must always ends with slash
relates: #268
=> fix(Front Generator): fix model relative path used in ejs templates

packages/front-generator/src/common/utils.test.ts, packages/front-generator/src/common/utils.ts
=> fix: backslashes are written to "import" statements on Windows

packages/front-generator/src/generators/react-typescript/blank-component/index.ts
=> [#39 🡆 master] fix: creating blank component doesn't add i18n key/value

packages/front-generator/src/generators/react-typescript/blank-component/index.ts
ticket #39
(cherry picked from commit bd59f618707251517118e505ba943053e95be07e)
=> [#39 🡆 release_20.1] fix: creating blank component doesn't add i18n key/value

docs-src/doc-component-repo/modules/cuba-react-ui/pages/file-upload.adoc, packages/cuba-react-core/src/app/Security.test.ts, packages/cuba-react-core/src/app/Security.ts, packages/cuba-react-ui/src/ui/FileUpload.tsx, packages/cuba-rest-js/src/cuba.ts, packages/cuba-rest-js/src/security.ts, packages/cuba-rest-js/test/security.spec.js
affects: @cuba-platform/react-core, @cuba-platform/react-ui, @cuba-platform/rest
ticket #286
=> [#286 🡆 master] fix: hide FileUpload drop area when not having sufficient permissions

docs-src/doc-component-repo/modules/cuba-react-ui/pages/file-upload.adoc, packages/cuba-react-core/src/app/Security.test.ts, packages/cuba-react-core/src/app/Security.ts, packages/cuba-react-ui/src/ui/FileUpload.tsx, packages/cuba-rest-js/src/cuba.ts, packages/cuba-rest-js/src/security.ts, packages/cuba-rest-js/test/security.spec.js
affects: @cuba-platform/react-core, @cuba-platform/react-ui, @cuba-platform/rest
ticket #286
(cherry picked from commit 02de8ec824b36d0d9276bd5cb41c1bd8631c2ba8)
=> [#286 🡆 release_20.1] fix: hide FileUpload drop area when not having sufficient permissions

packages/front-generator/src/generators/react-typescript/entity-cards/template/EntityCards.tsx.ejs, packages/front-generator/src/test/fixtures/react-client/src/app/entity-cards/MpgFavoriteCarCards.tsx
before apply default sort by updateTs, check that entity implemets updatable
relates: #120
=> fix(Front Generator): sort only updatable entites on EntityCards
