packages/cuba-react/src/ui/table/DataTable.tsx
packages/cuba-react/src/ui/table/DataTableHelpers.tsx

fix: support filters on non-displayed fields

---

packages/cuba-react/src/ui/table/DataTable.less
packages/cuba-react/src/ui/table/DataTableHelpers.tsx

fix(DataTable): long column titles are not fully shown

---

packages/cuba-react/.gitignore
packages/cuba-rest-js/.gitignore
packages/front-generator/src/generators/react-typescript/app/template/src/app/App.tsx

fix(Menu): SubMenu has no key prop console warning

---

.travis.yml
commitlint.config.js
package-lock.json
package.json

chore: setup commitlint

---

sample-car-rent/build.gradle
sample-car-rent/modules/core/web/WEB-INF/web.xml
sample-car-rent/modules/web/web/WEB-INF/web.xml

Add-on allows to generate entities: Administration > Data Generation > Generate Entities

Add datagen addon

---

README.md
packages/cuba-react-ui/src/ui/FormField.tsx
packages/cuba-react-ui/src/ui/form/Field.tsx

Backed field component customization

---

packages/cuba-react-ui/src/ui/table/DataTable.tsx
packages/cuba-react-ui/src/ui/table/DataTableCell.tsx
packages/cuba-react-ui/src/ui/table/DataTableHelpers.tsx

Data table code improvements and todo

---

.travis.yml
packages/front-generator/src/generators/react-typescript/entity-cards/template/EntityCards.tsx.ejs
packages/front-generator/src/generators/react-typescript/entity-management/template/Cards.tsx.ejs
packages/front-generator/src/test/fixtures/react-client/src/app/entity-cards/MpgFavoriteCarCards.tsx
packages/front-generator/src/test/fixtures/react-client/src/app/entity-management/CarCards.tsx
sample-car-rent/modules/core/db/init/postgres/10.create-db.sql
sample-car-rent/modules/core/db/update/postgres/20/200227-1-createIntIdTestEntity.sql
sample-car-rent/modules/core/db/update/postgres/20/200227-1-createStringIdTestEntity.sql
sample-car-rent/modules/global/src/com/company/scr/entity/test/IntIdTestEntity.java
sample-car-rent/modules/global/src/com/company/scr/entity/test/StringIdTestEntity.java
sample-car-rent/modules/global/src/com/company/scr/entity/test/messages.properties
sample-car-rent/modules/global/src/com/company/scr/persistence.xml
scripts/generate-react-client-scr.js
scripts/model/projectModel-scr.json
scripts/screens/int-id-cards.json
scripts/screens/string-id-cards.json

Fix screen generation for int id entity

---

packages/front-generator/src/generators/react-typescript/app/template/package.json
test-pup/react-client-scr/car-browse-list-paging.test.js

test: fix Puppeteer tests failing at CI

---

packages/cuba-react-core/src/data/Collection.tsx
packages/cuba-react-ui/src/ui/table/DataTable.tsx
packages/cuba-react-ui/src/ui/table/DataTableHelpers.tsx
packages/front-generator/src/generators/react-typescript/app/template/src/i18n/en.json
packages/front-generator/src/generators/react-typescript/app/template/src/i18n/ru.json

affects: @cuba-platform/react-core, @cuba-platform/react-ui, @cuba-platform/front-generator
related to #108

fix(DataTable): no error message when filtering fails

---

packages/cuba-react-ui/src/ui/Spinner.less
packages/cuba-react-ui/src/ui/Spinner.tsx
packages/front-generator/src/generators/react-typescript/app/template/src/app/App.css
packages/front-generator/src/generators/react-typescript/app/template/src/app/App.tsx
packages/front-generator/src/generators/react-typescript/app/template/src/app/CenteredLoader.css
packages/front-generator/src/generators/react-typescript/app/template/src/app/CenteredLoader.tsx
packages/front-generator/src/generators/react-typescript/app/template/src/app/common/Centered.css
packages/front-generator/src/generators/react-typescript/app/template/src/app/common/Centered.tsx
packages/front-generator/src/generators/react-typescript/app/template/src/app/header/AppHeader.css
packages/front-generator/src/generators/react-typescript/app/template/src/app/header/AppHeader.tsx
packages/front-generator/src/generators/react-typescript/app/template/src/app/login/Login.css
packages/front-generator/src/generators/react-typescript/app/template/src/app/login/Login.tsx

affects: @cuba-platform/react-ui, @cuba-platform/front-generator
related to #78

refactor(React): replace inline styles with RSCSS-conforming classes

---

packages/cuba-react-ui/src/ui/table/DataTable.tsx

fix(DataTable): only show columns allowed by user runtime permissions

---

packages/cuba-react-ui/src/ui/FileUpload.tsx
packages/cuba-react-ui/src/ui/ImagePreview.less
packages/cuba-react-ui/src/ui/ImagePreview.tsx
packages/cuba-react-ui/src/util/files.ts
packages/front-generator/src/generators/react-typescript/app/template/src/i18n/en.json
packages/front-generator/src/generators/react-typescript/app/template/src/i18n/ru.json

affects: @cuba-platform/react-ui, @cuba-platform/front-generator
related to #87

feat: improved image preview

---

docs-src/doc-component-repo/modules/client-react/nav.adoc
package-lock.json
package.json

chore: update Antora #183

---

packages/cuba-react-ui/src/ui/table/DataTableCustomFilter.tsx

fix(DataTable): error when applying in/notIn filter without adding items

---

packages/cuba-react-ui/src/ui/form/UuidInput.tsx
packages/cuba-react-ui/src/util/regex.ts

fix: relax UUID validation rules

---

.travis.yml

chore: allow snyk:monitor to fail at CI

---

packages/front-generator/src/common/constants.ts
packages/front-generator/src/generators/sdk/model/model-utils.ts
packages/front-generator/src/generators/sdk/services/queries-generation.ts
packages/front-generator/src/generators/sdk/services/services-generation.ts
packages/front-generator/src/test/generators/sdk/services/queries-generation.test.ts
packages/front-generator/src/test/test-commons.ts
packages/front-generator/test/e2e/expect/queries.ts

Add return type as generic param in rest queries

---

packages/front-generator/src/common/constants.ts
packages/front-generator/src/generators/sdk/model/model-utils.ts
packages/front-generator/src/generators/sdk/services/queries-generation.ts
packages/front-generator/src/generators/sdk/services/services-generation.ts
packages/front-generator/src/test/generators/sdk/services/queries-generation.test.ts
packages/front-generator/src/test/test-commons.ts
packages/front-generator/test/e2e/expect/queries.ts

feat(React): add entity as generic param to cuba app query call

---

packages/front-generator/src/common/base-generator.ts
packages/front-generator/src/test/common/base-generator.test.ts

fix(Front Generator): answers validation for question type INTEGER

---

packages/front-generator/src/test/generators/react-native/react-native-generator.test.ts

test: fix React Native generator test

---

packages/front-generator/src/test/fixtures/templates/i18nMappings.ts
packages/front-generator/src/test/fixtures/templates/i18nMappings.ts.ejs
packages/front-generator/src/test/generators/react-typrscript/react-generator-process-templates.test.ts
packages/front-generator/tsconfig.json

chore: generators - rework template processing test

---

CONTRIBUTING.md

docs: add coding conventions to CONTRIBUTING.md

---

packages/cuba-react-core/src/data/Instance.test.tsx
packages/cuba-react-core/src/data/Instance.tsx
packages/cuba-react-core/src/index.ts
packages/cuba-react-core/src/util/temporal.ts
packages/cuba-react-ui/src/ui/table/DataTableCustomFilter.tsx
packages/cuba-react-ui/src/ui/table/DataTableListEditorDateTimePicker.tsx

affects: @cuba-platform/react-core
related to #113

fix: datetime is saved with "random" amount of milliseconds

---

packages/front-generator/src/generators/sdk/sdk-generator.ts

fix: error when generating sdk:all #261

---

packages/front-generator/src/generators/sdk/model/entities-generation.ts
packages/front-generator/src/generators/sdk/model/model-utils.ts
packages/front-generator/src/generators/sdk/sdk-generator.ts
sample-car-rent/modules/global/src/com/company/scr/entity/Garage.java
sample-car-rent/modules/global/src/com/company/scr/entity/messages.properties
sample-car-rent/modules/global/src/com/company/scr/entity/messages_ru.properties
scripts/model/projectModel-scr.json

Reproduce #272 in sample-car-rent

Transient one to many association in scr

---

packages/cuba-react-ui/package.json

chore: fix copyfiles script for os windows

---

packages/cuba-react-core/package-lock.json
packages/cuba-react-core/package.json
packages/cuba-react-ui/package-lock.json
packages/cuba-react-ui/package.json
packages/cuba-react-ui/src/ui/form/Form.tsx
packages/cuba-rest-js/package-lock.json
packages/cuba-rest-js/package.json
packages/cuba-rest-js/test/cuba-app.spec.js
packages/front-generator/package-lock.json
packages/front-generator/package.json
packages/front-generator/src/generators/react-native/app/template/package.json
packages/front-generator/src/generators/sdk/model/entities-generation.ts

affects: @cuba-platform/react-core, @cuba-platform/react-ui, @cuba-platform/rest,
@cuba-platform/front-generator

chore: updated typesript version to 4.1.x

---

packages/cuba-react-ui/package-lock.json
packages/cuba-react-ui/package.json
packages/front-generator/.snyk
packages/front-generator/src/generators/react-typescript/app/template/i18n-message-packs/en.json
packages/front-generator/src/generators/react-typescript/app/template/i18n-message-packs/fr.json
packages/front-generator/src/generators/react-typescript/app/template/i18n-message-packs/ru.json
packages/front-generator/src/generators/react-typescript/app/template/i18n-message-packs/zh-cn.json
packages/front-generator/src/generators/react-typescript/app/template/package.json

after update antd version broke error messages
Api message changes: https://github.com/react-component/field-form/blob/master/src/utils/messages.ts

fix: fix antd error message templates

---

packages/cuba-react-core/src/data/Instance.tsx
packages/cuba-react-core/src/util/metadata.ts
packages/cuba-react-ui/src/ui/EntitySelectField.tsx
packages/cuba-react-ui/src/ui/table/DataTable.tsx
packages/cuba-react-ui/src/ui/table/DataTableCustomFilter.tsx
packages/cuba-rest-js/src/cuba.ts
packages/cuba-rest-js/src/util.ts
packages/cuba-rest-js/test/utlil.spec.js
packages/front-generator/src/generators/react-typescript/entity-cards/template/EntityCards.tsx.ejs
packages/front-generator/src/generators/react-typescript/entity-management-hooks/template/Cards.tsx.ejs
packages/front-generator/src/generators/react-typescript/entity-management-hooks/template/List.tsx.ejs
packages/front-generator/src/generators/react-typescript/entity-management-hooks/template/Table.tsx.ejs
packages/front-generator/src/generators/react-typescript/entity-management/template/Cards.tsx.ejs
packages/front-generator/src/generators/react-typescript/entity-management/template/List.tsx.ejs
packages/front-generator/src/generators/react-typescript/entity-management/template/Table.tsx.ejs
packages/front-generator/src/generators/sdk/model/entities-generation.ts
packages/front-generator/src/test/fixtures/react-client/src/app/entity-cards/MpgFavoriteCarCards.tsx
packages/front-generator/src/test/fixtures/react-client/src/app/entity-management/CarCards.tsx
packages/front-generator/src/test/fixtures/react-client/src/app/entity-management/CarList.tsx
packages/front-generator/src/test/fixtures/react-client/src/app/entity-management/CarTable.tsx
packages/front-generator/src/test/fixtures/react-client/src/app/entity-management/CarTableLowCase.tsx
packages/front-generator/src/test/fixtures/react-client/src/app/entity-management/HooksEMCardsBrowse.tsx
packages/front-generator/src/test/fixtures/react-client/src/app/entity-management/HooksEMListBrowse.tsx
packages/front-generator/src/test/fixtures/react-client/src/app/entity-management/HooksEMTableBrowse.tsx
packages/front-generator/src/test/fixtures/react-client/src/app/entity-management/StringIdMgtTableBrowse.tsx
scripts/generate-react-client-scr.js
scripts/screens/composite-key-entity-management-cards.json
scripts/screens/composite-key-entity-management-list.json

affects: @cuba-platform/react-core, @cuba-platform/react-ui, @cuba-platform/rest,
@cuba-platform/front-generator

feat: added support of editing and removing entities with composite keys

---

packages/cuba-react-core/src/app/MainStore.ts
packages/cuba-react-core/src/app/Security.ts
packages/cuba-react-ui/src/index.ts
packages/cuba-react-ui/src/ui/form/Form.tsx
packages/cuba-react-ui/src/util/mapCubaRestErrorToIntlId.ts
packages/cuba-rest-js/jest.config.js
packages/cuba-rest-js/src/cuba.ts
packages/cuba-rest-js/src/error.ts
packages/cuba-rest-js/test/cuba-app-lt-7-2.spec.js
packages/front-generator/src/generators/react-typescript/app/shared.ts
packages/front-generator/src/generators/react-typescript/app/template/i18n-message-packs/en.json
packages/front-generator/src/generators/react-typescript/app/template/i18n-message-packs/ru.json
packages/front-generator/src/generators/react-typescript/app/template/src/app/login/Login.tsx
packages/front-generator/src/generators/react-typescript/common/i18n.ts
packages/front-generator/src/generators/react-typescript/entity-management/entity-management-en.json
packages/front-generator/src/generators/react-typescript/entity-management/entity-management-fr.json
packages/front-generator/src/generators/react-typescript/entity-management/entity-management-ru.json
packages/front-generator/src/generators/react-typescript/entity-management/entity-management-zh-cn.json
packages/front-generator/src/test/generators/react-typrscript/common/i18n.test.ts

affects: @cuba-platform/react-ui, @cuba-platform/rest, @cuba-platform/front-generator
add error handler for ui info message about rest error

feat: info message error handler

---

.snyk
package-lock.json
packages/cuba-react-core/.snyk
packages/cuba-react-core/package-lock.json
packages/cuba-react-core/package.json
packages/cuba-react-ui/.snyk
packages/cuba-react-ui/package-lock.json
packages/cuba-react-ui/package.json
packages/cuba-rest-js/.snyk
packages/cuba-rest-js/package-lock.json
packages/cuba-rest-js/package.json
packages/front-generator/.snyk
packages/front-generator/package-lock.json
packages/front-generator/package.json
packages/front-generator/src/generators/react-typescript/app/template/package.json
packages/front-generator/src/generators/react-typescript/app/template/tsconfig.json

affects: @cuba-platform/react-core, @cuba-platform/react-ui, @cuba-platform/rest,
@cuba-platform/front-generator
BREAKING CHANGE:
updated typscript and react-scripts versions

fix: fixed installing issue with npm7

---

packages/cuba-react-core/src/data/Instance.tsx

affects: @cuba-platform/react-core

feat: return promise in DataInstanceStore.load #408

---

package-lock.json
packages/cuba-react-core/package-lock.json
packages/cuba-react-core/package.json
packages/cuba-react-ui/package-lock.json
packages/cuba-react-ui/package.json
packages/cuba-rest-js/package-lock.json
packages/cuba-rest-js/package.json
packages/front-generator/package-lock.json
packages/front-generator/package.json
packages/front-generator/src/generators/react-typescript/app/template/package.json
packages/front-generator/src/test/common/base-generator.test.ts
packages/front-generator/src/test/common/test-utils.ts

affects: @cuba-platform/react-core, @cuba-platform/react-ui, @cuba-platform/rest,
@cuba-platform/front-generator

chore: update typescript to 4.4.3

---

packages/front-generator/src/generators/react-typescript/app/template/package-lock.json

fix: npm error when running simple application #474
